apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-ht3a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-ht3a
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-ht3a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-ht3a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-ht3a
    spec:
      containers:
      - image: quay.io/qijing/release-e2e-deploy-tenant/appstudio/dc-metro-map-ht3a@sha256:a52ff61c8e6f445d9e76c846e44cf3d3af71dd3e5cdda513fad250a85a176e62
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
